export const TIME_CONSTANTS = {
	IDLE_THRESHOLD: 30000,
	SAVE_INTERVAL: 10000,
	UI_FLASH_DURATION: 1000,
	NAVIGATION_DELAY: 0,
} as const;

export const SCORE_CONSTANTS = {
	TIME_NORMALIZATION_MAX: 5 * 60 * 1000,
	SCROLL_NORMALIZATION_MAX: 100,
	SCORE_MULTIPLIER: 100,
	WEIGHTS: {
		TIME: 0.3,
		SCROLL: 0.2,
		ENGAGEMENT: 0.3,
		FREQUENCY: 0.2,
	},
} as const;

export const DATA_LIMITS = {
	DEFAULT_ACTIVITY_LIMIT: 100,
	DEFAULT_HISTORY_LIMIT: 2000,
	DEFAULT_PERIOD_DAYS: 7,
} as const;

export const DATE_CONSTANTS = {
	WEEK_IN_MS: 7 * 24 * 60 * 60 * 1000,
	DAY_IN_MS: 24 * 60 * 60 * 1000,
	HOUR_IN_MS: 60 * 60 * 1000,
	MINUTE_IN_MS: 60 * 1000,
	SECOND_IN_MS: 1000,
} as const;

export const UI_CONSTANTS = {
	SCROLL_MAX_PERCENTAGE: 100,
	PERCENTAGE_MULTIPLIER: 100,
	DB_VERSION: 1,
	DEFAULT_PERIOD_OPTION: "7",
	PERIOD_OPTIONS: {
		ONE_DAY: 1,
		ONE_WEEK: 7,
		ONE_MONTH: 30,
	},
} as const;

export const INITIAL_VALUES = {
	ZERO: 0,
	EMPTY_ARRAY_INDEX: 0,
} as const;
